### ISSUE TITLE
Parse markdown within html tags

### ISSUE THREAD

**Issue by LostKobrakai** [RobertDober/earmark_parser#119]
https://babelmark.github.io/?text=%3Csmall%3ESome+%5BGoogle%5D(https%3A%2F%2Fwww.google.com%2F).%3C%2Fsmall%3E

Markdown within html tags doesn't seem to be parsed/converted.

**Comment by RobertDober** [comment]
IIUC as an intermediate solution we could also parse lines in the form

`<(.*?)>(.*)</\1>` as html, would that be enough to fix?
I guess I can do this quickly, well I am a little bit blocked in Germany (not far from you actually, Chiemsee, LOL) waiting to access Austria because of Boris, but maybe within a week or so.

BTW all myy best wishes to the Elixir community in Poland!!!!!

**Comment by RobertDober** [comment]
Sorry OP was from Augsburg, @gitneko does not reveal her location, I respect this of course

**Comment by RobertDober** [comment]
Hmm I guess I need to look at the code as I do not really understand what you want if it is not to parse 
`<(.*?)>(.*)</\1>` ?

Maybe could you make a PR with some failing test cases?

**Comment by RobertDober** [comment]
For now I understand the following
1. You need the markdown parsed inside HTML 
2. You need the `<(.*?)>(.*)</\1>` parsed correctly too, and that is probably implied by 1 anyway

I do not know about whitelisting though?

**Comment by RobertDober** [comment]
Ok I have looked into it and I would prefer not to implement this before 1.5. You say this feature is needed, but for whom is it needed, do we have this kind of html in ex_docs frequently?

**Comment by RobertDober** [comment]
Sorry cannot do this in the current version in any reasonable time
