### ISSUE TITLE
Fenced code in list GFM/commonmark compatability

### ISSUE THREAD

**Issue by garazdawi** [RobertDober/earmark_parser#131]
Hello!

I was using earmark through ex_doc and notice that fenced code in a list seemed to be parsed incorrectly. Both Markdown.pl, GFM and CommonMark seem to agree that 

````
- ```
  a
  ```
````

should be parsed as:

```html
<ul>
<li><code>
a
</code></li>
</ul>
```

while Earmark parses it as

```html
<ul>
<li><code>
  a
</code></li>
</ul>
```

I was about to start work on a patch when I saw that the [in list](https://github.com/RobertDober/earmark_parser/blob/master/test/acceptance/ast/fenced_code_blocks_test.exs#L69-L90) testcase explicitly tests the current behavior. So I'm wondering if there is a reason for it?

**Comment by RobertDober** [comment]
Thank you for this report.

I do not know the reason, I never explicitly checked this against reference implementations, BTW are you not missing a `<pre>...</pre>` in your snippet? Otherwise it shouldn't make a difference.

Anyway looks like a bug to me, so a PR with a corrected test would be happily accepted. ❤️

**Comment by garazdawi** [comment]
> BTW are you not missing a `<pre>...</pre>` in your snippet

I copy-pasted the content from what Markdown.pl gave, and there is no `<pre>` in there... GFM and commonmark do however include the `<pre>`... 

> Anyway looks like a bug to me, so a PR with a corrected test would be happily accepted. :heart:

I'll see what I can come up with!
